services:
  database:
    image: 'postgres:latest'
    ports:
      - '6432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=suryatest'
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - '~/volumes/suryatest-ppob/postgres:/var/lib/postgresql/data'
