logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.ggrmtest.ppob: INFO

spring:
  application:
    name: Ecommerce Backend
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      poolName: Hikari
      auto-commit: false
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    properties:
      hibernate:
        default_schema: ppob
    hibernate:
      ddl-auto: update
    open-in-view: true
  liquibase:
    change-log: classpath:db/changelog/master.xml
    default-schema: ppob
    contexts: dev

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

security:
  jwt:
    secret-key: a2f8da686fa44c03135dab60fbbca9e351251ada7f908904d25e6fd7489447fc
    expiration-time: 3600000

server:
  port: 8080
